# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'userpanel.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QGroupBox,
    QLabel, QLineEdit, QPushButton, QSizePolicy,
    QTabWidget, QTextEdit, QWidget)

class Ui_panel(object):
    def setupUi(self, panel):
        if not panel.objectName():
            panel.setObjectName(u"panel")
        panel.setWindowModality(Qt.ApplicationModal)
        panel.setEnabled(True)
        panel.resize(500, 310)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(panel.sizePolicy().hasHeightForWidth())
        panel.setSizePolicy(sizePolicy)
        panel.setAcceptDrops(True)
        self.func_option = QGroupBox(panel)
        self.func_option.setObjectName(u"func_option")
        self.func_option.setEnabled(True)
        self.func_option.setGeometry(QRect(20, 20, 340, 100))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.func_option.sizePolicy().hasHeightForWidth())
        self.func_option.setSizePolicy(sizePolicy1)
        self.func_option.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.func_option.setFlat(False)
        self.t2s_check = QCheckBox(self.func_option)
        self.t2s_check.setObjectName(u"t2s_check")
        self.t2s_check.setEnabled(True)
        self.t2s_check.setGeometry(QRect(125, 25, 100, 20))
        sizePolicy.setHeightForWidth(self.t2s_check.sizePolicy().hasHeightForWidth())
        self.t2s_check.setSizePolicy(sizePolicy)
        self.t2s_check.setChecked(True)
        self.cps_check = QCheckBox(self.func_option)
        self.cps_check.setObjectName(u"cps_check")
        self.cps_check.setEnabled(True)
        self.cps_check.setGeometry(QRect(125, 60, 100, 20))
        sizePolicy.setHeightForWidth(self.cps_check.sizePolicy().hasHeightForWidth())
        self.cps_check.setSizePolicy(sizePolicy)
        self.cps_check.setChecked(True)
        self.sub_check = QCheckBox(self.func_option)
        self.sub_check.setObjectName(u"sub_check")
        self.sub_check.setEnabled(True)
        self.sub_check.setGeometry(QRect(20, 60, 100, 20))
        sizePolicy.setHeightForWidth(self.sub_check.sizePolicy().hasHeightForWidth())
        self.sub_check.setSizePolicy(sizePolicy)
        self.sub_check.setChecked(True)
        self.auto_check = QCheckBox(self.func_option)
        self.auto_check.setObjectName(u"auto_check")
        self.auto_check.setEnabled(True)
        self.auto_check.setGeometry(QRect(20, 25, 100, 20))
        sizePolicy.setHeightForWidth(self.auto_check.sizePolicy().hasHeightForWidth())
        self.auto_check.setSizePolicy(sizePolicy)
        self.auto_check.setChecked(True)
        self.to_github = QPushButton(self.func_option)
        self.to_github.setObjectName(u"to_github")
        self.to_github.setEnabled(True)
        self.to_github.setGeometry(QRect(230, 55, 90, 30))
        sizePolicy.setHeightForWidth(self.to_github.sizePolicy().hasHeightForWidth())
        self.to_github.setSizePolicy(sizePolicy)
        self.to_content = QPushButton(self.func_option)
        self.to_content.setObjectName(u"to_content")
        self.to_content.setEnabled(True)
        self.to_content.setGeometry(QRect(230, 20, 90, 30))
        sizePolicy.setHeightForWidth(self.to_content.sizePolicy().hasHeightForWidth())
        self.to_content.setSizePolicy(sizePolicy)
        self.info_inputer = QTabWidget(panel)
        self.info_inputer.setObjectName(u"info_inputer")
        self.info_inputer.setEnabled(True)
        self.info_inputer.setGeometry(QRect(20, 135, 460, 165))
        sizePolicy1.setHeightForWidth(self.info_inputer.sizePolicy().hasHeightForWidth())
        self.info_inputer.setSizePolicy(sizePolicy1)
        self.info_inputer.setIconSize(QSize(15, 15))
        self.info_inputer.setDocumentMode(True)
        self.info_inputer.setMovable(True)
        self.auto_option = QWidget()
        self.auto_option.setObjectName(u"auto_option")
        self.auto_flow = QGroupBox(self.auto_option)
        self.auto_flow.setObjectName(u"auto_flow")
        self.auto_flow.setGeometry(QRect(0, 10, 270, 115))
        sizePolicy1.setHeightForWidth(self.auto_flow.sizePolicy().hasHeightForWidth())
        self.auto_flow.setSizePolicy(sizePolicy1)
        self.auto_flow.setFlat(True)
        self.flow_class = QCheckBox(self.auto_flow)
        self.flow_class.setObjectName(u"flow_class")
        self.flow_class.setEnabled(True)
        self.flow_class.setGeometry(QRect(25, 20, 20, 20))
        sizePolicy.setHeightForWidth(self.flow_class.sizePolicy().hasHeightForWidth())
        self.flow_class.setSizePolicy(sizePolicy)
        self.flow_class.setChecked(True)
        self.flow_tag = QCheckBox(self.auto_flow)
        self.flow_tag.setObjectName(u"flow_tag")
        self.flow_tag.setEnabled(True)
        self.flow_tag.setGeometry(QRect(60, 20, 20, 20))
        sizePolicy.setHeightForWidth(self.flow_tag.sizePolicy().hasHeightForWidth())
        self.flow_tag.setSizePolicy(sizePolicy)
        self.flow_tag.setChecked(True)
        self.flow_text = QCheckBox(self.auto_flow)
        self.flow_text.setObjectName(u"flow_text")
        self.flow_text.setEnabled(True)
        self.flow_text.setGeometry(QRect(95, 20, 20, 20))
        sizePolicy.setHeightForWidth(self.flow_text.sizePolicy().hasHeightForWidth())
        self.flow_text.setSizePolicy(sizePolicy)
        self.flow_text.setChecked(True)
        self.flow_title = QCheckBox(self.auto_flow)
        self.flow_title.setObjectName(u"flow_title")
        self.flow_title.setEnabled(True)
        self.flow_title.setGeometry(QRect(130, 20, 20, 20))
        sizePolicy.setHeightForWidth(self.flow_title.sizePolicy().hasHeightForWidth())
        self.flow_title.setSizePolicy(sizePolicy)
        self.flow_title.setChecked(True)
        self.flow_note = QCheckBox(self.auto_flow)
        self.flow_note.setObjectName(u"flow_note")
        self.flow_note.setEnabled(True)
        self.flow_note.setGeometry(QRect(165, 20, 20, 20))
        sizePolicy.setHeightForWidth(self.flow_note.sizePolicy().hasHeightForWidth())
        self.flow_note.setSizePolicy(sizePolicy)
        self.flow_note.setChecked(True)
        self.flow_image = QCheckBox(self.auto_flow)
        self.flow_image.setObjectName(u"flow_image")
        self.flow_image.setEnabled(True)
        self.flow_image.setGeometry(QRect(200, 20, 20, 20))
        sizePolicy.setHeightForWidth(self.flow_image.sizePolicy().hasHeightForWidth())
        self.flow_image.setSizePolicy(sizePolicy)
        self.flow_image.setChecked(True)
        self.flow_page = QCheckBox(self.auto_flow)
        self.flow_page.setObjectName(u"flow_page")
        self.flow_page.setEnabled(True)
        self.flow_page.setGeometry(QRect(235, 20, 20, 20))
        sizePolicy.setHeightForWidth(self.flow_page.sizePolicy().hasHeightForWidth())
        self.flow_page.setSizePolicy(sizePolicy)
        self.flow_page.setChecked(True)
        self.label_class = QLabel(self.auto_flow)
        self.label_class.setObjectName(u"label_class")
        self.label_class.setGeometry(QRect(25, 40, 20, 70))
        sizePolicy.setHeightForWidth(self.label_class.sizePolicy().hasHeightForWidth())
        self.label_class.setSizePolicy(sizePolicy)
        self.label_class.setInputMethodHints(Qt.ImhMultiLine)
        self.label_class.setTextFormat(Qt.PlainText)
        self.label_class.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_text = QLabel(self.auto_flow)
        self.label_text.setObjectName(u"label_text")
        self.label_text.setGeometry(QRect(95, 40, 20, 70))
        sizePolicy.setHeightForWidth(self.label_text.sizePolicy().hasHeightForWidth())
        self.label_text.setSizePolicy(sizePolicy)
        self.label_text.setInputMethodHints(Qt.ImhMultiLine)
        self.label_text.setTextFormat(Qt.PlainText)
        self.label_text.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_page = QLabel(self.auto_flow)
        self.label_page.setObjectName(u"label_page")
        self.label_page.setGeometry(QRect(235, 40, 20, 70))
        sizePolicy.setHeightForWidth(self.label_page.sizePolicy().hasHeightForWidth())
        self.label_page.setSizePolicy(sizePolicy)
        self.label_page.setInputMethodHints(Qt.ImhMultiLine)
        self.label_page.setTextFormat(Qt.PlainText)
        self.label_page.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_image = QLabel(self.auto_flow)
        self.label_image.setObjectName(u"label_image")
        self.label_image.setGeometry(QRect(200, 40, 20, 70))
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setInputMethodHints(Qt.ImhMultiLine)
        self.label_image.setTextFormat(Qt.PlainText)
        self.label_image.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_note = QLabel(self.auto_flow)
        self.label_note.setObjectName(u"label_note")
        self.label_note.setGeometry(QRect(165, 40, 20, 70))
        sizePolicy.setHeightForWidth(self.label_note.sizePolicy().hasHeightForWidth())
        self.label_note.setSizePolicy(sizePolicy)
        self.label_note.setInputMethodHints(Qt.ImhMultiLine)
        self.label_note.setTextFormat(Qt.PlainText)
        self.label_note.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_title = QLabel(self.auto_flow)
        self.label_title.setObjectName(u"label_title")
        self.label_title.setGeometry(QRect(130, 40, 20, 70))
        sizePolicy.setHeightForWidth(self.label_title.sizePolicy().hasHeightForWidth())
        self.label_title.setSizePolicy(sizePolicy)
        self.label_title.setInputMethodHints(Qt.ImhMultiLine)
        self.label_title.setTextFormat(Qt.PlainText)
        self.label_title.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_tag = QLabel(self.auto_flow)
        self.label_tag.setObjectName(u"label_tag")
        self.label_tag.setGeometry(QRect(60, 40, 20, 70))
        sizePolicy.setHeightForWidth(self.label_tag.sizePolicy().hasHeightForWidth())
        self.label_tag.setSizePolicy(sizePolicy)
        self.label_tag.setInputMethodHints(Qt.ImhMultiLine)
        self.label_tag.setTextFormat(Qt.PlainText)
        self.label_tag.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.auto_func = QGroupBox(self.auto_option)
        self.auto_func.setObjectName(u"auto_func")
        self.auto_func.setGeometry(QRect(295, 10, 146, 115))
        sizePolicy1.setHeightForWidth(self.auto_func.sizePolicy().hasHeightForWidth())
        self.auto_func.setSizePolicy(sizePolicy1)
        self.chk_check = QCheckBox(self.auto_func)
        self.chk_check.setObjectName(u"chk_check")
        self.chk_check.setEnabled(True)
        self.chk_check.setGeometry(QRect(20, 20, 100, 20))
        sizePolicy.setHeightForWidth(self.chk_check.sizePolicy().hasHeightForWidth())
        self.chk_check.setSizePolicy(sizePolicy)
        self.chk_check.setChecked(True)
        self.tem_check = QCheckBox(self.auto_func)
        self.tem_check.setObjectName(u"tem_check")
        self.tem_check.setEnabled(True)
        self.tem_check.setGeometry(QRect(20, 50, 120, 20))
        sizePolicy.setHeightForWidth(self.tem_check.sizePolicy().hasHeightForWidth())
        self.tem_check.setSizePolicy(sizePolicy)
        self.tem_check.setChecked(True)
        self.del_check = QCheckBox(self.auto_func)
        self.del_check.setObjectName(u"del_check")
        self.del_check.setEnabled(True)
        self.del_check.setGeometry(QRect(20, 80, 120, 20))
        sizePolicy.setHeightForWidth(self.del_check.sizePolicy().hasHeightForWidth())
        self.del_check.setSizePolicy(sizePolicy)
        self.del_check.setChecked(True)
        self.info_inputer.addTab(self.auto_option, "")
        self.book_info = QWidget()
        self.book_info.setObjectName(u"book_info")
        self.subtitle = QLineEdit(self.book_info)
        self.subtitle.setObjectName(u"subtitle")
        self.subtitle.setGeometry(QRect(65, 55, 375, 30))
        sizePolicy.setHeightForWidth(self.subtitle.sizePolicy().hasHeightForWidth())
        self.subtitle.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(11)
        self.subtitle.setFont(font)
        self.subtitle.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.subtitle.setClearButtonEnabled(True)
        self.lable_title = QLabel(self.book_info)
        self.lable_title.setObjectName(u"lable_title")
        self.lable_title.setEnabled(True)
        self.lable_title.setGeometry(QRect(5, 15, 60, 30))
        sizePolicy2 = QSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.lable_title.sizePolicy().hasHeightForWidth())
        self.lable_title.setSizePolicy(sizePolicy2)
        self.lable_title.setSizeIncrement(QSize(0, 0))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.lable_title.setFont(font1)
        self.lable_title.setAlignment(Qt.AlignCenter)
        self.lable_title.setIndent(0)
        self.title = QLineEdit(self.book_info)
        self.title.setObjectName(u"title")
        self.title.setGeometry(QRect(65, 15, 280, 30))
        sizePolicy.setHeightForWidth(self.title.sizePolicy().hasHeightForWidth())
        self.title.setSizePolicy(sizePolicy)
        self.title.setFont(font)
        self.title.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.title.setClearButtonEnabled(True)
        self.lable_isbn = QLabel(self.book_info)
        self.lable_isbn.setObjectName(u"lable_isbn")
        self.lable_isbn.setEnabled(True)
        self.lable_isbn.setGeometry(QRect(5, 95, 60, 30))
        sizePolicy2.setHeightForWidth(self.lable_isbn.sizePolicy().hasHeightForWidth())
        self.lable_isbn.setSizePolicy(sizePolicy2)
        self.lable_isbn.setSizeIncrement(QSize(0, 0))
        self.lable_isbn.setFont(font1)
        self.lable_isbn.setAlignment(Qt.AlignCenter)
        self.lable_isbn.setIndent(0)
        self.volume = QLineEdit(self.book_info)
        self.volume.setObjectName(u"volume")
        self.volume.setGeometry(QRect(350, 15, 90, 30))
        sizePolicy.setHeightForWidth(self.volume.sizePolicy().hasHeightForWidth())
        self.volume.setSizePolicy(sizePolicy)
        self.volume.setFont(font)
        self.volume.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.volume.setClearButtonEnabled(True)
        self.isbn = QLineEdit(self.book_info)
        self.isbn.setObjectName(u"isbn")
        self.isbn.setGeometry(QRect(65, 95, 190, 30))
        sizePolicy.setHeightForWidth(self.isbn.sizePolicy().hasHeightForWidth())
        self.isbn.setSizePolicy(sizePolicy)
        self.isbn.setFont(font)
        self.isbn.setInputMethodHints(Qt.ImhDigitsOnly|Qt.ImhPreferNumbers)
        self.isbn.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.isbn.setClearButtonEnabled(True)
        self.from_opf = QPushButton(self.book_info)
        self.from_opf.setObjectName(u"from_opf")
        self.from_opf.setGeometry(QRect(260, 95, 180, 30))
        sizePolicy.setHeightForWidth(self.from_opf.sizePolicy().hasHeightForWidth())
        self.from_opf.setSizePolicy(sizePolicy)
        self.from_opf.setFont(font)
        self.info_inputer.addTab(self.book_info, "")
        self.edit_info = QWidget()
        self.edit_info.setObjectName(u"edit_info")
        self.lable_writer = QLabel(self.edit_info)
        self.lable_writer.setObjectName(u"lable_writer")
        self.lable_writer.setEnabled(True)
        self.lable_writer.setGeometry(QRect(5, 15, 60, 30))
        sizePolicy2.setHeightForWidth(self.lable_writer.sizePolicy().hasHeightForWidth())
        self.lable_writer.setSizePolicy(sizePolicy2)
        self.lable_writer.setSizeIncrement(QSize(0, 0))
        self.lable_writer.setFont(font1)
        self.lable_writer.setAlignment(Qt.AlignCenter)
        self.lable_writer.setIndent(0)
        self.writer = QLineEdit(self.edit_info)
        self.writer.setObjectName(u"writer")
        self.writer.setGeometry(QRect(65, 15, 160, 30))
        sizePolicy.setHeightForWidth(self.writer.sizePolicy().hasHeightForWidth())
        self.writer.setSizePolicy(sizePolicy)
        self.writer.setFont(font)
        self.writer.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.writer.setClearButtonEnabled(True)
        self.introducer = QLineEdit(self.edit_info)
        self.introducer.setObjectName(u"introducer")
        self.introducer.setGeometry(QRect(285, 55, 160, 30))
        sizePolicy.setHeightForWidth(self.introducer.sizePolicy().hasHeightForWidth())
        self.introducer.setSizePolicy(sizePolicy)
        self.introducer.setFont(font)
        self.introducer.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.introducer.setClearButtonEnabled(True)
        self.painter = QLineEdit(self.edit_info)
        self.painter.setObjectName(u"painter")
        self.painter.setGeometry(QRect(285, 15, 160, 30))
        sizePolicy.setHeightForWidth(self.painter.sizePolicy().hasHeightForWidth())
        self.painter.setSizePolicy(sizePolicy)
        self.painter.setFont(font)
        self.painter.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.painter.setClearButtonEnabled(True)
        self.translator = QLineEdit(self.edit_info)
        self.translator.setObjectName(u"translator")
        self.translator.setGeometry(QRect(65, 55, 160, 30))
        sizePolicy.setHeightForWidth(self.translator.sizePolicy().hasHeightForWidth())
        self.translator.setSizePolicy(sizePolicy)
        self.translator.setFont(font)
        self.translator.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.translator.setClearButtonEnabled(True)
        self.lable_epuber = QLabel(self.edit_info)
        self.lable_epuber.setObjectName(u"lable_epuber")
        self.lable_epuber.setEnabled(True)
        self.lable_epuber.setGeometry(QRect(225, 95, 60, 30))
        sizePolicy2.setHeightForWidth(self.lable_epuber.sizePolicy().hasHeightForWidth())
        self.lable_epuber.setSizePolicy(sizePolicy2)
        self.lable_epuber.setSizeIncrement(QSize(0, 0))
        self.lable_epuber.setFont(font1)
        self.lable_epuber.setAlignment(Qt.AlignCenter)
        self.lable_epuber.setIndent(0)
        self.lable_painter = QLabel(self.edit_info)
        self.lable_painter.setObjectName(u"lable_painter")
        self.lable_painter.setEnabled(True)
        self.lable_painter.setGeometry(QRect(225, 15, 60, 30))
        sizePolicy2.setHeightForWidth(self.lable_painter.sizePolicy().hasHeightForWidth())
        self.lable_painter.setSizePolicy(sizePolicy2)
        self.lable_painter.setSizeIncrement(QSize(0, 0))
        self.lable_painter.setFont(font1)
        self.lable_painter.setAlignment(Qt.AlignCenter)
        self.lable_painter.setIndent(0)
        self.epuber = QLineEdit(self.edit_info)
        self.epuber.setObjectName(u"epuber")
        self.epuber.setGeometry(QRect(285, 95, 160, 30))
        sizePolicy.setHeightForWidth(self.epuber.sizePolicy().hasHeightForWidth())
        self.epuber.setSizePolicy(sizePolicy)
        self.epuber.setFont(font)
        self.epuber.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.epuber.setClearButtonEnabled(True)
        self.inputer = QLineEdit(self.edit_info)
        self.inputer.setObjectName(u"inputer")
        self.inputer.setGeometry(QRect(65, 95, 160, 30))
        sizePolicy.setHeightForWidth(self.inputer.sizePolicy().hasHeightForWidth())
        self.inputer.setSizePolicy(sizePolicy)
        self.inputer.setFont(font)
        self.inputer.setAlignment(Qt.AlignJustify|Qt.AlignVCenter)
        self.inputer.setClearButtonEnabled(True)
        self.lable_inputer = QLabel(self.edit_info)
        self.lable_inputer.setObjectName(u"lable_inputer")
        self.lable_inputer.setEnabled(True)
        self.lable_inputer.setGeometry(QRect(5, 95, 60, 30))
        sizePolicy2.setHeightForWidth(self.lable_inputer.sizePolicy().hasHeightForWidth())
        self.lable_inputer.setSizePolicy(sizePolicy2)
        self.lable_inputer.setSizeIncrement(QSize(0, 0))
        self.lable_inputer.setFont(font1)
        self.lable_inputer.setAlignment(Qt.AlignCenter)
        self.lable_inputer.setIndent(0)
        self.lable_introducer = QLabel(self.edit_info)
        self.lable_introducer.setObjectName(u"lable_introducer")
        self.lable_introducer.setEnabled(True)
        self.lable_introducer.setGeometry(QRect(225, 55, 60, 30))
        sizePolicy2.setHeightForWidth(self.lable_introducer.sizePolicy().hasHeightForWidth())
        self.lable_introducer.setSizePolicy(sizePolicy2)
        self.lable_introducer.setSizeIncrement(QSize(0, 0))
        self.lable_introducer.setFont(font1)
        self.lable_introducer.setAlignment(Qt.AlignCenter)
        self.lable_introducer.setIndent(0)
        self.lable_translator = QLabel(self.edit_info)
        self.lable_translator.setObjectName(u"lable_translator")
        self.lable_translator.setEnabled(True)
        self.lable_translator.setGeometry(QRect(5, 55, 60, 30))
        sizePolicy2.setHeightForWidth(self.lable_translator.sizePolicy().hasHeightForWidth())
        self.lable_translator.setSizePolicy(sizePolicy2)
        self.lable_translator.setSizeIncrement(QSize(0, 0))
        self.lable_translator.setFont(font1)
        self.lable_translator.setAlignment(Qt.AlignCenter)
        self.lable_translator.setIndent(0)
        self.info_inputer.addTab(self.edit_info, "")
        self.summary_inputer = QWidget()
        self.summary_inputer.setObjectName(u"summary_inputer")
        self.summary = QTextEdit(self.summary_inputer)
        self.summary.setObjectName(u"summary")
        self.summary.setGeometry(QRect(15, 15, 430, 110))
        sizePolicy.setHeightForWidth(self.summary.sizePolicy().hasHeightForWidth())
        self.summary.setSizePolicy(sizePolicy)
        font2 = QFont()
        font2.setPointSize(11)
        font2.setBold(False)
        self.summary.setFont(font2)
        self.summary.viewport().setProperty("cursor", QCursor(Qt.IBeamCursor))
        self.summary.setAcceptDrops(True)
        self.summary.setFrameShape(QFrame.Box)
        self.summary.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.summary.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.summary.setTabChangesFocus(True)
        self.summary.setAcceptRichText(False)
        self.info_inputer.addTab(self.summary_inputer, "")
        self.launch_start = QPushButton(panel)
        self.launch_start.setObjectName(u"launch_start")
        self.launch_start.setEnabled(False)
        self.launch_start.setGeometry(QRect(370, 25, 90, 60))
        sizePolicy.setHeightForWidth(self.launch_start.sizePolicy().hasHeightForWidth())
        self.launch_start.setSizePolicy(sizePolicy)
        self.launch_start.setFont(font)
        self.config_reset = QPushButton(panel)
        self.config_reset.setObjectName(u"config_reset")
        self.config_reset.setGeometry(QRect(370, 90, 90, 30))
        sizePolicy.setHeightForWidth(self.config_reset.sizePolicy().hasHeightForWidth())
        self.config_reset.setSizePolicy(sizePolicy)
        self.func_option.raise_()
        self.launch_start.raise_()
        self.info_inputer.raise_()
        self.config_reset.raise_()
        QWidget.setTabOrder(self.auto_check, self.t2s_check)
        QWidget.setTabOrder(self.t2s_check, self.to_content)
        QWidget.setTabOrder(self.to_content, self.sub_check)
        QWidget.setTabOrder(self.sub_check, self.cps_check)
        QWidget.setTabOrder(self.cps_check, self.to_github)
        QWidget.setTabOrder(self.to_github, self.launch_start)
        QWidget.setTabOrder(self.launch_start, self.info_inputer)
        QWidget.setTabOrder(self.info_inputer, self.flow_class)
        QWidget.setTabOrder(self.flow_class, self.flow_tag)
        QWidget.setTabOrder(self.flow_tag, self.flow_text)
        QWidget.setTabOrder(self.flow_text, self.flow_title)
        QWidget.setTabOrder(self.flow_title, self.flow_note)
        QWidget.setTabOrder(self.flow_note, self.flow_image)
        QWidget.setTabOrder(self.flow_image, self.flow_page)
        QWidget.setTabOrder(self.flow_page, self.chk_check)
        QWidget.setTabOrder(self.chk_check, self.tem_check)
        QWidget.setTabOrder(self.tem_check, self.del_check)
        QWidget.setTabOrder(self.del_check, self.title)
        QWidget.setTabOrder(self.title, self.volume)
        QWidget.setTabOrder(self.volume, self.subtitle)
        QWidget.setTabOrder(self.subtitle, self.isbn)
        QWidget.setTabOrder(self.isbn, self.from_opf)
        QWidget.setTabOrder(self.from_opf, self.writer)
        QWidget.setTabOrder(self.writer, self.painter)
        QWidget.setTabOrder(self.painter, self.translator)
        QWidget.setTabOrder(self.translator, self.introducer)
        QWidget.setTabOrder(self.introducer, self.inputer)
        QWidget.setTabOrder(self.inputer, self.epuber)
        QWidget.setTabOrder(self.epuber, self.summary)

        self.retranslateUi(panel)
        self.auto_check.toggled.connect(self.info_inputer.setVisible)
        self.auto_check.toggled.connect(self.info_inputer.setEnabled)

        self.info_inputer.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(panel)
    # setupUi

    def retranslateUi(self, panel):
        panel.setWindowTitle(QCoreApplication.translate("panel", u"STERA-X", None))
        self.func_option.setTitle(QCoreApplication.translate("panel", u"\u529f\u80fd\u9009\u9879", None))
        self.t2s_check.setText(QCoreApplication.translate("panel", u"\u7e41\u7b80\u8f6c\u6362", None))
        self.cps_check.setText(QCoreApplication.translate("panel", u"\u56fe\u7247\u538b\u7f29", None))
        self.sub_check.setText(QCoreApplication.translate("panel", u"\u5b57\u4f53\u5b50\u96c6\u5316", None))
        self.auto_check.setText(QCoreApplication.translate("panel", u"\u81ea\u52a8\u5316\u5904\u7406", None))
        self.to_github.setText(QCoreApplication.translate("panel", u"\u8bbf\u95ee\u4e3b\u9875", None))
        self.to_content.setText(QCoreApplication.translate("panel", u"\u6253\u5f00\u76ee\u5f55", None))
        self.auto_flow.setTitle(QCoreApplication.translate("panel", u"\u81ea\u52a8\u5316\u6d41\u7a0b", None))
        self.label_class.setText(QCoreApplication.translate("panel", u"\u6837\n"
"\u5f0f\n"
"\u6574\n"
"\u7406", None))
        self.label_text.setText(QCoreApplication.translate("panel", u"\u6587\n"
"\u672c\n"
"\u5904\n"
"\u7406", None))
        self.label_page.setText(QCoreApplication.translate("panel", u"\u9875\n"
"\u9762\n"
"\u590d\n"
"\u67e5", None))
        self.label_image.setText(QCoreApplication.translate("panel", u"\u56fe\n"
"\u7247\n"
"\u7248\n"
"\u5f0f", None))
        self.label_note.setText(QCoreApplication.translate("panel", u"\u6ce8\n"
"\u91ca\n"
"\u751f\n"
"\u6210", None))
        self.label_title.setText(QCoreApplication.translate("panel", u"\u7ae0\n"
"\u8282\n"
"\u91cd\n"
"\u6784", None))
        self.label_tag.setText(QCoreApplication.translate("panel", u"\u6807\n"
"\u7b7e\n"
"\u89c4\n"
"\u8303", None))
        self.auto_func.setTitle(QCoreApplication.translate("panel", u"\u9644\u52a0\u529f\u80fd", None))
        self.chk_check.setText(QCoreApplication.translate("panel", u"\u6837\u5f0f\u68c0\u67e5", None))
        self.tem_check.setText(QCoreApplication.translate("panel", u"\u751f\u6210\u6807\u51c6\u6a21\u677f", None))
        self.del_check.setText(QCoreApplication.translate("panel", u"\u6e05\u7406\u591a\u4f59\u6587\u4ef6", None))
        self.info_inputer.setTabText(self.info_inputer.indexOf(self.auto_option), QCoreApplication.translate("panel", u"\u81ea\u52a8\u5316\u9009\u9879", None))
        self.subtitle.setPlaceholderText(QCoreApplication.translate("panel", u"\u526f\u6807\u9898", None))
        self.lable_title.setText(QCoreApplication.translate("panel", u"\u4e66\u540d", None))
        self.title.setPlaceholderText(QCoreApplication.translate("panel", u"\u6807\u9898\uff08\u5fc5\u586b\uff09", None))
        self.lable_isbn.setText(QCoreApplication.translate("panel", u"ISBN", None))
        self.volume.setPlaceholderText(QCoreApplication.translate("panel", u"\u5377\u53f7", None))
        self.isbn.setPlaceholderText(QCoreApplication.translate("panel", u"13\u4f4d\u6570\u5b57\uff08\u5fc5\u586b\uff09", None))
        self.from_opf.setText(QCoreApplication.translate("panel", u"\u4eceOPF\u4e2d\u83b7\u53d6", None))
        self.info_inputer.setTabText(self.info_inputer.indexOf(self.book_info), QCoreApplication.translate("panel", u"\u4e66\u7c4d\u4fe1\u606f", None))
        self.lable_writer.setText(QCoreApplication.translate("panel", u"\u4f5c\u8005", None))
        self.writer.setPlaceholderText(QCoreApplication.translate("panel", u"\uff08\u5fc5\u586b\uff09", None))
        self.introducer.setPlaceholderText(QCoreApplication.translate("panel", u"\uff08\u5fc5\u586b\uff09", None))
        self.painter.setPlaceholderText(QCoreApplication.translate("panel", u"\uff08\u5fc5\u586b\uff09", None))
        self.translator.setPlaceholderText(QCoreApplication.translate("panel", u"\uff08\u5fc5\u586b\uff09", None))
        self.lable_epuber.setText(QCoreApplication.translate("panel", u"EPUB", None))
        self.lable_painter.setText(QCoreApplication.translate("panel", u"\u63d2\u753b", None))
        self.epuber.setPlaceholderText(QCoreApplication.translate("panel", u"\uff08\u5fc5\u586b\uff09", None))
        self.inputer.setPlaceholderText(QCoreApplication.translate("panel", u"\uff08\u5fc5\u586b\uff09", None))
        self.lable_inputer.setText(QCoreApplication.translate("panel", u"\u5f55\u5165", None))
        self.lable_introducer.setText(QCoreApplication.translate("panel", u"\u56fe\u6e90", None))
        self.lable_translator.setText(QCoreApplication.translate("panel", u"\u8bd1\u8005", None))
        self.info_inputer.setTabText(self.info_inputer.indexOf(self.edit_info), QCoreApplication.translate("panel", u"\u5236\u4f5c\u4fe1\u606f", None))
        self.summary.setPlaceholderText(QCoreApplication.translate("panel", u"\uff08\u82e5\u7559\u7a7a\u5219\u4e0d\u751f\u6210\u7b80\u4ecb\u9875\uff09", None))
        self.info_inputer.setTabText(self.info_inputer.indexOf(self.summary_inputer), QCoreApplication.translate("panel", u"\u7b80\u4ecb\u6587\u672c", None))
        self.launch_start.setText(QCoreApplication.translate("panel", u"\u5f00\u59cb", None))
        self.config_reset.setText(QCoreApplication.translate("panel", u"\u8fd8\u539f\u914d\u7f6e", None))
    # retranslateUi

